name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Publish
      run: dotnet publish --framework net5.0 --configuration Release --self-contained -r win10-x64

      
    - name: Upload cfapp98 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cfapp98
        path: D:\a\GitHub-CICD-Test-01\GitHub-CICD-Test-01\cfapp98\bin\Release\net5.0\win10-x64\publish\

  deploy_local:
    needs: build
    runs-on: self-hosted
 
    steps: 
    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\cfapp98_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\cfapp98_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\cfapp98 cfapp98_bak
        md c:\pub\cfapp98
    
    - name: Download new binaries to the local app
      uses: actions/download-artifact@v2
      with:
        name: cfapp98
        path: c:\pub\cfapp98
        
  deploy_remote:
    needs: deploy_local
    runs-on: self-hosted 
    environment:
      name: GitHub-CICD-Test-01.Prod
      
    steps: 
    - name: Prepare remote folders
      run: |
        Remove-Item '\\WIN2019DC03\c$\pub\cfapp98_bak1' -Recurse -ErrorAction Ignore
        Remove-Item '\\WIN2019DC03\c$\pub\cfapp98_bak' -Recurse -ErrorAction Ignore
        ren \\WIN2019DC03\c$\pub\cfapp98 cfapp98_bak
        md \\WIN2019DC03\c$\pub\cfapp98

    - name: Download new binaries to the remote app
      uses: actions/download-artifact@v2
      with:
        name: cfapp98
        path: \\WIN2019DC03\c$\pub\cfapp98
